# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: # Or as an environment variable
          HESLO: ${{secrets.HESLO}}

    steps:
      - uses: actions/checkout@v3
      - name: show password
        run: echo "Password is:${{secrets.HESLO}}"   
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm run test:run
